version: '3.9'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "PA55w0rd2024"
    ports:
      - "1433:1433"
    networks:
      - backend
  api: 
    image: store:dev
    container_name: api
    build:
      context: ./store
      dockerfile: Dockerfile
    environment:
      - DBServer=sqlserver
      - DBPort=1433
      - DBUser=SA
      - DBPassword=PA55w0rd2024
      - Database=Fiap
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - backend  
    depends_on:
      - sqlserver

  apipayment: 
    image: payment:dev
    container_name: apipayment
    build:
      context: ./payment
      dockerfile: Dockerfile
    ports:
      - "8480:8480"
      - "8481:8481"
    networks:
      - backend  
    depends_on:
      - api
      
networks:
  backend:
    driver: bridge