version: '3.9'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_payment
    ports:
      - "5675:5672"
      - "15675:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  payment:
    build:
      context: ./payment
      dockerfile: Dockerfile
    container_name: api_payment
    ports:
      - "8480:8480"
    environment:
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__UserName=guest
      - RabbitMQ__Password=guest
      - DB_CONNECTION_STRING=Server=sqlserver;Database=PaymentDB;User=SA;Password=PA55w0rd2024;
    depends_on:
      - rabbitmq
      - sqlserver
    networks:
      - backend

  # payment_tests:
  #   build:
  #     context: ./payment
  #     dockerfile: Dockerfile.tests
  #   container_name: payment_tests
  #   command: dotnet test --logger "console;verbosity=detailed"
  #   depends_on:
  #     - rabbitmq
  #     - sqlserver
  #   networks:
  #     - backend

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_payment
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "PA55w0rd2024"
    ports:
      - "1434:1433"
    networks:
      - backend

networks:
  backend:
    driver: bridge
