apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: payment-api
  template:
    metadata:
      labels:
        app: payment-api
    spec:
      imagePullSecrets:
      - name: acr-secret
      containers:
      - name: payment-api
        image: mycontainerregistrytechchallenge.azurecr.io/payment:latest
        ports:
        - containerPort: 8480
