apiVersion: v1
kind: Service
metadata:
  name: payment-api
spec:
  selector:
    app: payment-api
  ports:
    - name: http
      protocol: TCP
      port: 8480
      targetPort: 8480
  type: LoadBalancer
